name: ollama

on:
  push:
  workflow_dispatch:

jobs:
  test-with-ollama:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run Ollama Docker image and pull gemma2:2b
        run: |
          mkdir -p ~/.ollama/models
          docker run -v ollama:/home/runner/.ollama --name ollama ollama/ollama pull gemma2:2b
          docker run -d -v ollama:/home/runner/.ollama -p 11434:11434 --name ollama ollama/ollama
          sleep 5
          time curl -i http://localhost:11434
      - name: npm ci
        run: |
            npm ci
      - name: npm run test
        run: |
            npm run test
